### ISSUE TITLE
Search 功能无法正常搜索设备

### ISSUE THREAD

**Issue by Suaig** [libdriver/ds18b20#17]
### Version

2.0

### Describe the bug

我使用Proteus 仿真驱动DS18B20，移植完驱动之后，能够正常使用Read test 和register test。 但是连接多个设备（3个）调用Search test的时候，得到的设备数总是0，我试图再Search 函数里监控k的变量。k一直读取到的是0x03，既然，两个bit都是1. 就被判定为没有设备。
下图是串口输出：
![image](https://github.com/user-attachments/assets/54ff0e4c-b8b6-48af-aa3a-4f064cb7d8b3)
下图是电路图：
![image](https://github.com/user-attachments/assets/da15c734-3f98-4863-907e-e09ccdbedbc5)
我尝试定位问题，但是无法获得原因。keil 使用得V5编译器， Proteus 使用得是8.17 sp2

代码附件如下：
[ds18b20.zip](https://github.com/user-attachments/files/18035730/ds18b20.zip)

### Reproduce

NA

### Expected behavior

Search 功能能正常搜索到设备

**Comment by libdriver** [comment]
Thank you very much for using LibDriver. Each DS18B20 chip has a 64 bit globally unique ROM. Using a search chip or search alarm essentially searches for ROM. For Proteus simulation programs, the first step is to ensure that the ROM serial number of each DS18B20 is not duplicated. You can check the component attribute editing or read the ROM serial number of each chip in batches to check if it is unique. If the ROM serial number is duplicated, it will cause retrieval abnormalities. The chip manufacturer will ensure the global uniqueness of the ROM.

非常感谢您使用LibDriver，DS18B20真实的芯片每一个都有一个64bit全球唯一ROM，使用搜索芯片或者搜索报警本质是搜索ROM，对于Proteus仿真程序应首先确保每一个DS18B20的ROM序列号不重复，您可以查看元件属性编辑或分次读取每一个芯片的ROM序列号，检查是否唯一，如果ROM序列号重复会导致检索异常，真实出厂的芯片生产制造商会保证ROM的全球唯一性。

**Comment by Suaig** [comment]
> Thank you very much for using LibDriver. Each DS18B20 chip has a 64 bit globally unique ROM. Using a search chip or search alarm essentially searches for ROM. For Proteus simulation programs, the first step is to ensure that the ROM serial number of each DS18B20 is not duplicated. You can check the component attribute editing or read the ROM serial number of each chip in batches to check if it is unique. If the ROM serial number is duplicated, it will cause retrieval abnormalities. The chip manufacturer will ensure the global uniqueness of the ROM.
> 
> 非常感谢您使用LibDriver，DS18B20真实的芯片每一个都有一个64bit全球唯一ROM，使用搜索芯片或者搜索报警本质是搜索ROM，对于Proteus仿真程序应首先确保每一个DS18B20的ROM序列号不重复，您可以查看元件属性编辑或分次读取每一个芯片的ROM序列号，检查是否唯一，如果ROM序列号重复会导致检索异常，真实出厂的芯片生产制造商会保证ROM的全球唯一性。

非常感谢您的回复，经过仔细比对每一个bit的时序，发现问题出在微小延时上。长延时的误差可以忽略不计，微小延时的误差导致了search功能搜索失败。经过特别在 2us这样的延时地方校准延时。驱动成功读取到了多个设备的ROM CODE.

Thank you very much for your response. After carefully comparing the timing of each bit, I found that the issue was due to slight delays. The error in long delays can be ignored, but the error in slight delays caused the search function to fail. After specifically calibrating the delay at around 2 microseconds, the driver successfully read the ROM codes of multiple devices.

**Comment by libdriver** [comment]
Congratulation!

恭喜您调试成功！
